マンデルブロ集合描画アプリの追加
uchan-nos/mikanos pull request #29
Opened 2021-06-20 08:50 UTC by PickledChair

## マンデルブロ集合描画アプリ `mandel`
`mandel` コマンドでマンデルブロ集合が描画されたウィンドウを表示するだけのアプリです。

マンデルブロ集合は、計算の規則自体はシンプルであるにも関わらず視覚的に楽しい数学的対象の一例です。そのため、本アプリは規模としては小さいながらもシンプルに美しいという良さがあります。

また、このアプリは「ゼロからのOS自作入門」における22章終了時点までのMikanOSの機能で動作します。同書籍の学習者が学習中に自作アプリを作るときのヒントになる可能性もあります。

![mandel アプリのスクリーンショット](https://user-images.githubusercontent.com/41382894/122666438-1f23f480-d1e8-11eb-97c2-05c544e2ddbd.png)

2021-06-21 01:35 UTC, uchan-nos requested changes
全体的には綺麗なコードだと思います。
手元で動作確認したところ、正常に動きました。

いくつかレビューコメントを書きましたので、対応をお願いします。

2021-06-21 01:35 UTC, uchan-nos commented on apps/mandel/mandel.cpp
> +}
C++ 標準の `<complex>` ヘッダに入っている `std::complex` というクラスを使うと以下のように書けます。

```
int MandelConverge(std::complex<double> z) {
  const auto c = z;
  const int nmax = 100;

  for (int n = 0; n < nmax && std::norm(z) <= 4; ++n) {
    z = z*z + c;
    ++n;
  }

  return n;
}
```

元のプログラムでは z = z^2 + c の計算が複雑で理解しにくかったです。
`z = z*z + c` と書ける上記の案の方が良いかなと思いますが、いかがでしょうか。

2021-06-21 01:35 UTC, uchan-nos commented on apps/mandel/mandel.cpp
> +      int depth = MandelConverge(xmin + xstep*x, ymin + ystep*y);
`std::complex` を使う場合、引数に `{}` を付ける必要があります。

```
      int depth = MandelConverge({xmin + xstep*x, ymin + ystep*y});
```

2021-06-21 01:35 UTC, uchan-nos commented on apps/mandel/mandel.cpp
> +#include <algorithm>
ヘッダファイルはアルファベット順にソートしてください。
（既存のアプリでソートされてない物があるのは、ごめんなさい）

他のレビューコメントで提案した `std::complex` を使う場合、`<complex>` のインクルードも必要です。

2021-06-21 02:48 UTC, PickledChair commented
レビューありがとうございます。確かに `std::complex` を用いた方がすっきり書けますね！ のちほど書き直してみます。

2021-06-21 10:13 UTC, PickledChair commented
レビューで指摘いただいた箇所を直しました。また、 #30 で `stars` アプリに見られた問題が `mandel` アプリにもあったので、全く同じ方法で対処しました。

2021-06-22 08:35 UTC, uchan-nos requested changes
非常に些細な点ですが1つだけ対応をお願いします。

2021-06-22 08:35 UTC, uchan-nos commented on apps/mandel/Makefile
> +
空行が余分に入ってしまってますね……

最終行の改行文字は 1 つだけで大丈夫です。
（GitHub 上で赤いマークで「No newline at end of file」と表示されず、
かつ余分な空行もない、そんな状態を目指してください）

2021-06-22 10:14 UTC, PickledChair commented on apps/mandel/Makefile
> +
エディタが余分に改行を挿入したのに気づかずpushしてしまいました。チェックありがとうございます！

2021-06-23 12:16 UTC, merged

2021-06-23 12:16 UTC, uchan-nos commented
どうもありがとうございました！