長さがわかっているデータの出力にPrintToFD関数を使わないようにする
uchan-nos/mikanos pull request #41
Opened 2022-07-30 10:41 UTC by mikecat

fix #39

以下のコマンドにおいて、長さがわかっているデータの出力に `PrintToFD` 関数を使わないようにします。

* `cat`
* `usbtest`

これにより、以下の効果が得られます。

* `PrintToFD` 関数の脆弱性 (`vsprintf` 関数によるバッファオーバーラン) の影響を受けず、長いデータを出力できる
* 値 `0x00` のバイトを含むデータでも出力できる

2022-07-30 13:09 UTC, mikecat commented
何故か微妙にデータが化けますね…

![mikanos-cat-bake-20220730](https://user-images.githubusercontent.com/6667599/181915768-5dc2cbf4-5c6d-46e4-82ff-09387c02e821.png)

2022-07-30 13:46 UTC, mikecat commented
バッファサイズを1024バイトから1025バイトにしたら化けなくなったようだ。

`files_[1]->Write` 関数に問題があるかもしれない。

だとすれば、`PrintToFD`関数には直接関係しなそうなのでプルリクするにしても別にしたい。

2022-08-09 05:28 UTC, uchan-nos requested changes

2022-08-09 05:28 UTC, uchan-nos commented on kernel/terminal.cpp
> +        size_t readSize = ReadDelim(*fd, '\n', u8buf, sizeof(u8buf));
変数名（ `readSize` ）はアンダースコア区切りでお願いします。

2022-08-09 12:33 UTC, mikecat commented on kernel/terminal.cpp
> +        size_t readSize = ReadDelim(*fd, '\n', u8buf, sizeof(u8buf));
修正しました。

2022-08-10 09:49 UTC, uchan-nos commented
このコミットの効果を検証するために `cat night.bmp > night2.bmp` を master 版 MikanOS でやってみたら GP が発生した。
![GP exception](https://user-images.githubusercontent.com/1825663/183871625-85c63408-2d3e-4016-a26f-689b3815fc9d.png)

2022-08-10 09:50 UTC, merged

2022-08-10 09:53 UTC, uchan-nos commented
マージ後GPが出なくなり、night2.bmpでもデータが化けないことを確認した