簡易テキストエディタを追加
uchan-nos/mikanos pull request #46
Opened 2022-07-31 23:03 UTC by mikecat

簡易テキストエディタアプリケーション `tedit` を追加します。

* 編集するファイル名をコマンドラインで指定して起動する
  * ファイル名を指定しなくても起動はできるが、保存はできなくなる
* `Ctrl+S` で上書き保存
* 編集後保存せずに閉じようとすると、確認ダイアログを表示する
  * マウス左クリックまたはAlt+(選択肢の頭文字)で選択

(例えば)以下には対応していません。

* 別名保存
* テキストのコピペ
* 検索・置換
* 横スクロール

2022-08-01 02:39 UTC, uchan-nos commented
@mikecat 
たくさんのプルリクをありがとうございます。
プルリクが一度に来すぎて混乱しているので、可能であれば一度に 1 つに抑えて欲しいです。
まず最初に対応すべきプルリクはどれですか？

2022-08-01 10:46 UTC, mikecat commented
プルリク出しすぎでしたか…申し訳ありません。  
今あるアイデアを実装しきった後は、1個ずつにしたいと思います。  
優先順位は以下のようになると思います。

1. fat::FileDescriptor::Write のバグ修正
   * 修正内容がシンプル
   * 通常の操作で踏む可能性がある
2. ファイルを見つける関数の改善
   * 不都合を踏みやすい
   * 脆弱性の修正を含む
3. 長さがわかっているデータの出力にPrintToFD関数を使わないようにする
   * 脆弱性の修正を含む
4. コマンドの右側のスペースのトリム (予定)
   * 「ファイルを見つける関数の改善」を適用すると発生する不都合への対処
   * workaroundは存在する
5. ls -l の実装 (予定)
   * 不都合の修正ではなく新規機能の追加である
6. 簡易テキストエディタを追加
   * 不都合の修正ではなく新規機能の追加である
7. キー操作でマウスを動かせるようにする (予定)
   * 不都合の修正ではなく新規機能の追加である
8. PrintToFD() がバッファオーバーランしないようにする
   * (「長さがわかっているデータ～」を適用すれば)踏む可能性が低い

2022-08-11 00:35 UTC, uchan-nos requested changes

2022-08-11 00:39 UTC, uchan-nos commented
> プルリクが一度に来すぎて混乱しているので、可能であれば一度に 1 つに抑えて欲しいです。

と書きましたが、今回プルリクに対応してみて、少し思いが変わりました。
複数のプルリクがあっても、優先順位を明示してくだされば対応しやすかったです。

2022-08-12 10:34 UTC, mikecat commented
コメントありがとうございます。
修正は数日後以降になると思います。

`main` から `exit` ではなく `return` するようにする変更も反映させたいですが、Git上でどのようにすればいいでしょうか？

> > プルリクが一度に来すぎて混乱しているので、可能であれば一度に 1 つに抑えて欲しいです。
>
> と書きましたが、今回プルリクに対応してみて、少し思いが変わりました。
> 複数のプルリクがあっても、優先順位を明示してくだされば対応しやすかったです。

わかりました。
では今issueにあげている分もプルリクにしますね。
優先順位は

1. ファイルの書き込み時に更新日時を更新する
2. ターミナルにおける特殊文字の扱いの改善
3. コマンド実行時のターミナルの描画の改善
4. ターミナルのカーソルの点滅が止まったら復元する
5. ディスクイメージをGitの管理から外す

でお願いします。

2022-08-18 00:35 UTC, uchan-nos commented
> main から exit ではなく return するようにする変更も反映させたいですが、Git上でどのようにすればいいでしょうか？

すみません、これの返信をしていませんでした。
text-editor ブランチを最新の master ブランチに対して rebase し、その後 text-editor ブランチを force push してもらうのが王道かと思います。

操作が煩雑になるし、exit を使うコードでも動かないわけではないので、まずはこのままマージを目指すのがいいかなと思います。

2022-08-18 00:48 UTC, merged